name: Verification Tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        # macos-13 for Intel Mac, macos-14 for Apple Chips Mac
        os: [ubuntu-22.04, windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew check -PCICD=GitHubActions # the "clean" task would fail on GitHub Actions: https://github.com/sunny-chung/kdatetime-multiplatform/actions/runs/8213856523/job/22465724399
